### ISSUE TITLE
Update the tagline

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#102]
Issue Type
----------

- Feature request

Expected Behavior
-----------------

The current tagline is good but should be catchier.

* Refine the current tagline
* Keep it Short
    * Think mobile
    * Think elevator speech

**Comment by rgreinho** [comment]
Assigned to @toughee.

**Comment by Toughee** [comment]
Updated the tagline with the comments for the issues in mind. This is what I made:

<h2>
<strong>Make your voice heard!</strong>
<br></h2>

<h3>Request Yo Racks is a free, responsive web application that allows you to request bike corrals to be installed directly to the City of Austin, Texas.
</h3>

Let me know if everything looks okay. I'll be making a pull request for this soon.

**Comment by Toughee** [comment]
Review @rgreinho

**Comment by rgreinho** [comment]
Tag line idea: 

> Rack it up!

**Comment by Toughee** [comment]
That sounds good. Adding it right now.
