### ISSUE TITLE
Update the preview design

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#103]
Issue Type
----------

- Feature request

Current Behavior
----------------

The preview is not very appealing.

Expected Behavior
-----------------

Make the preview more engaging, more modern.

Possible Solution
-----------------

* Shadow around the copy button
* Make the preview more card looking(?)

**Comment by rgreinho** [comment]
The component should also have a bit more styling options. Right now the view containing it does most of the work, but the heavy lifting should actually come from the component itself.

**Comment by Toughee** [comment]
@rgreinho I would like to claim this issue

**Comment by rgreinho** [comment]
No problem @Toughee. This issue is yours now ;)

**Comment by rgreinho** [comment]
Closed by  request-yo-racks/web#133
