### ISSUE TITLE
Update "What to do next?" section

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#104]
Issue Type
----------

- Feature request

Current Behavior
----------------

The "What to do next?" could be clearer and could also be its own component.

Expected Behavior
-----------------

See v2 design (#82)

Possible Solution
-----------------

* The Caution message needs to be emphasized. It is important that the people know they have to go talk to the businesses supporting their request.
* The caution message could be a step 0
* We should emphasize that there is no guarantee of having a bike rack

**Comment by Toughee** [comment]
Updated "What to do" section. Put the caution underneath preview before submitting following new UX design. Copy of caution message change below:


<p>"Make sure the business you chose supports your request. Without it, the request will be not be processed. You must also go talk to the businesses supporting their request in order for the bike rack to be installed. </p>
<strong>There is no guarantee that the bike rack will be installed."</strong></p>
</div>

Will be making a PR soon for the changes

**Comment by Toughee** [comment]
Review @rgreinho
