### ISSUE TITLE
Change header image

### ISSUE THREAD

**Issue by 2echoi** [request-yo-racks/web#125]
Issue Type
----------

- Feature request

Current Behavior
----------------

The height of the image is too small. Also, the image is too dark. It doesn't match the design.

Expected Behavior
-----------------

- The height of the image should be 250 px. 
- The header image will be changed for better visual design: 
https://www.goodfreephotos.com/united-states/colorado/denver/bike-on-bike-rack-in-denver-colorado.jpg.php

**Comment by rgreinho** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @rgreinho.
