### ISSUE TITLE
Create Preview component

### ISSUE THREAD

**Issue by Toughee** [request-yo-racks/web#148]
Issue Type
----------

- Feature request

Current Behavior
----------------

There is no component for the preview section inside the web repository.

Expected Behavior
-----------------

Web application should show preview section. 

![preview-ryr-img](https://user-images.githubusercontent.com/21093554/47969908-d6719a00-e043-11e8-8d05-50d0260b55aa.JPG)

Possible Solution
-----------------

React component made for preview section.

Steps to Reproduce
------------------

1. Application runs without any errors
2. Section looks exactly like V2 design
3. Run through ` npm ci ` to perform all tests 

My Environment
----------------
```
Browser(s):
  Google Canary Version 72.0.3601.0 (Official Build) canary (32-bit)
System Version: Windows 8.1 
```

**Comment by rgreinho** [comment]
The preview component was completed as part of #183.
