### ISSUE TITLE
Implement a mechanism to use a resource URL for the API server

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#20]
## Issue Type
- Feature request

## Expected Behavior

Being able to specify the base URL for the api server depending on the environment. For instance, the base URL for the API server would be `http://localhost:8000` if run locally, or `http://api.192.168.99.100.nip.io` if run on Minikube.

## Current Behavior

The URLs are hardcoded.

## Possible Solution

Link: https://stackoverflow.com/questions/39566875/what-is-the-preferred-way-to-set-phase-specific-environments-in-polymer-apps

**Comment by rgreinho** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by AndrewGibson27** [comment]
@rgreinho I'll take this one.

**Comment by rgreinho** [comment]
Oh cool! I am curious to see how you'll solve that one!
