### ISSUE TITLE
Update the global layout

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#32]
Issue Type
----------

- Feature request

Expected Behavior
-----------------

Update the main layout to make it more engaging for the users.

One layout I found online and I like very much is the [Skyscrapers website template by Freepik ](https://image.freepik.com/free-vector/skyscrapers-website-template_23-2147535945.jpg). I think we could get some inspiration from it.

![template](https://image.freepik.com/free-vector/skyscrapers-website-template_23-2147535945.jpg)

I envision each section being a step (i.e. "Select a location"). As each section has the shape of a triangle pointing down, it naturally guides the user toward the next step/action, making the interaction more user-friendly.

Current Behavior
----------------

The site works, but is not really appealing.

Context
-------

Improving the look and feel of the webapp.

**Comment by rgreinho** [comment]
Yep, I started to work on that one. Sorry I forgot to assign myself to this issue.

**Comment by arc6789** [comment]
ok cool no worries!

**Comment by rgreinho** [comment]
Sneak preview of where I'm headed:
![image](https://user-images.githubusercontent.com/6969134/37074384-2b64cfbc-2192-11e8-8074-e5abba4c5474.png)

A PR will follow soon and as always, all your comments/feedback/suggestions are very appreciated.

**Comment by rgreinho** [comment]
Some progress on this issue, I am almost ready to submit a PR for y'all to review.

Desktop version:
![image](https://user-images.githubusercontent.com/6969134/37155046-79353450-22a7-11e8-8015-115030e428ad.png)

Mobile version:
![image](https://user-images.githubusercontent.com/6969134/37155074-8cfbfcf8-22a7-11e8-8f2b-26278da8a66c.png)
