### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#36]
Issue Type
----------

- Feature request

Expected Behavior
-----------------

Create a simple landing page using polymer elements. The page must be simple and will be hosted on github.io until we release the first version.

Possible Solution
-----------------

Get some inspiration from the [landing page](https://polymerelements.github.io/app-layout/templates/landing-page/) demo.

**Comment by rgreinho** [comment]
Here is the link for the source code which goes with the demo: https://github.com/PolymerElements/app-layout/tree/master/templates/landing-page

**Comment by arc6789** [comment]
I am assuming this is going to be its own git repo?

**Comment by rgreinho** [comment]
I would prefer to have it in the `web` project. I want to simply host it on github-pages by waiting we have our first version ready.

**Comment by rgreinho** [comment]
This is not necessary anymore as the first version of the project is going live soon.
