### ISSUE TITLE
Cannot launch the pattern library

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#37]
Issue Type
----------

- Bug report

Expected Behavior
-----------------

Being able to launch astrum to see the pattern library.

Current Behavior
----------------

An error message appears on the page:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/6969134/37011326-35f9ef58-20b5-11e8-8e57-f986221a4552.png">

Possible Solution
-----------------

It looks like some files were not checked in. Adding them should solve the problem.

Steps to Reproduce
--------------------

1. `cd "${RYR_PROJECT_DIR}/web"`
2. Launch `polymer serve`
3. Go to http://127.0.0.1:8081/public/pattern-library/index.html

Context
-------

Attempting to look at the pattern library.

Your Environment
----------------

* Version used: master@a145804
* Browser Name and version: chrome/firefox
* Operating System and version (desktop or mobile): OSX

**Comment by rgreinho** [comment]
@UX-Chris I think this one is for you ;)

**Comment by UX-Chris** [comment]
I think I just capitalized the group names instead of titles. I'm not getting the error so let me know if it's not fixed
