### ISSUE TITLE
Write unit tests for ryr-location

### ISSUE THREAD

**Issue by AndrewGibson27** [request-yo-racks/web#40]
Issue Type
----------
- Feature request

Expected Behavior
-----------------
This component should have unit tests and should be cleaned up along the way to make the tests more granular.

Current Behavior
----------------
No tests, and some duplicate logic in the component.

I'll be using the built-in Polymer test suite.

**Comment by AndrewGibson27** [comment]
I'm on this and am nearing completion!

**Comment by rgreinho** [comment]
Awesome! 👍
