### ISSUE TITLE
Give some style to the preview component

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#53]
Issue Type
----------

- Feature request

Expected Behavior
-----------------

The preview component should do more than simply returning some text. It should show the user that an actual message is being generated.

Current Behavior
----------------

The text is simply dropped in the preview section of `view1`.

Possible Solution
-----------------

Do some CSS magic.

**Comment by rgreinho** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/request-yo-racks/web/issues/10 (Turn the preview component into its own element), https://github.com/request-yo-racks/web/issues/8 (Create a style guide), and https://github.com/request-yo-racks/web/issues/12 (Create shared style to ensure design coherence).

**Comment by rgreinho** [comment]
@chanduvkp is working on this issue.

**Comment by chanduvkp** [comment]
created a branch with "issue/give-some-style-to-the-preview-component". Since this is logged as issue so prefixed with "issue"

**Comment by chanduvkp** [comment]
@rgreinho -  changes are commited in the branch named "bugfix/give-some-style-to-the-preview-component". Please review
