### ISSUE TITLE
Lo Fi Wireframe Website

### ISSUE THREAD

**Issue by 2echoi** [request-yo-racks/web#61]
Issue Type
----------

- Feature request

Expected Behavior
-----------------

This is a rough sketch for Request-Yo-Request webpage. To make it look user-friendly, the content has to be simple and concise. It may be changed in the future.

Possible Solution
-----------------

![img_7363](https://user-images.githubusercontent.com/32255194/37879824-33d6a6d2-3044-11e8-8577-aa255fa2540e.jpg)
![img_7364](https://user-images.githubusercontent.com/32255194/37879851-b7a092d4-3044-11e8-9489-d19cd2bc082f.jpg)

**Comment by rgreinho** [comment]
Superseded by #82.
