### ISSUE TITLE
Change footer layout

### ISSUE THREAD

**Issue by UX-Chris** [request-yo-racks/web#62]
Issue Type

- Feature request

Current Behavior
----------------

The footer currently has a description about the project and links to social media.

Expected Behavior
-----------------

Only have links to the pages of the project, no description, and add social media icons.

Possible Solution
-----------------

Steps to Reproduce (for bugs)
-----------------------------

1. cd "${RYR_PROJECT_DIR}/web"
2. polymer serve
3. open http://127.0.0.1:8081/
4. Scroll down to the footer

Context
-------

Trying to make the footer simpler and add icons for a more visual layout.

Your Environment
----------------

* Version used: master branch (0b78f4)
* Browser Name and version: Chrome 65.0.3325.181 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): OS X 10.11.6

**Comment by rgreinho** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/request-yo-racks/web/issues/32 (Update the global layout), and https://github.com/request-yo-racks/web/issues/26 (Change the Font).
