### ISSUE TITLE
Change text and icon color on green sections

### ISSUE THREAD

**Issue by UX-Chris** [request-yo-racks/web#70]
Issue Type
----------

- Bug report

Current Behavior
----------------

The text and icons on the green background sections is black and hard to read.

Expected Behavior
-----------------

If the text and icons on the green background sections is white they will be easier to read.

Possible Solution
-----------------

Connect the colors to the shared-styles colors and change the color from black to white.

Steps to Reproduce (for bugs)
-----------------------------

1. Polymer serve
2. Open http://127.0.0.1:8081/

Context
-------

This would improve the readability and visuals of the site.

Your Environment
----------------

* Version used: 5995da4
* Browser Name and version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): OS El Capitan Version 10.11.6

**Comment by rgreinho** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/request-yo-racks/web/issues/26 (Change the Font), and https://github.com/request-yo-racks/web/issues/62 (Change footer layout).

**Comment by rgreinho** [comment]
@UX-Chris Please refer to the design for v2 (Issue #82) to update this section. 

What do you think of making the "How it works section" it's own component?

**Comment by UX-Chris** [comment]
This issue is no longer necessary as it will be addressed in the v2 design.
