### ISSUE TITLE
Turn the application into a Progressive Web Application

### ISSUE THREAD

**Issue by UX-Chris** [request-yo-racks/web#74]
Issue Type
----------
- Feature request

Current Behavior
----------------

Currently the application loads slow and has subpar performance.

Expected Behavior
-----------------

Provide faster loading and a better, more reliable experience.

Possible Solution
-----------------

Follow the process to create a PWA:
[Checklist from Google](https://developers.google.com/web/progressive-web-apps/checklist)

**Comment by rgreinho** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/request-yo-racks/web/issues/11 (Turn the suggestion list into its own element), https://github.com/request-yo-racks/web/issues/10 (Turn the preview component into its own element), and https://github.com/request-yo-racks/web/issues/9 (Turn the email templatizer into an element project).

**Comment by rgreinho** [comment]
Switching to React made this issue obsolete.
