### ISSUE TITLE
Implement Lighthouse Audits

### ISSUE THREAD

**Issue by UX-Chris** [request-yo-racks/web#75]
Issue Type
----------

- Feature request

Current Behavior
----------------

The application has not been run through audits.

Expected Behavior
-----------------

Running lighthouse audits will report on how to improve the application.

Possible Solution
-----------------

Implement [Lighthouse audits](https://developers.google.com/web/tools/lighthouse/) to improve the performance and accessibility.

**Comment by rgreinho** [comment]
Duplicate of #79.
