### ISSUE TITLE
Add audit validations to CircleCI

### ISSUE THREAD

**Issue by UX-Chris** [request-yo-racks/web#76]
Issue Type
----------

- Feature request

Current Behavior
----------------

CircleCI does not run audit validations.

Expected Behavior
-----------------

CircleCI will run a Lighthouse audit and provide the score to ensure the application stays above acceptable standards.

Possible Solution
-----------------

Implement audit validations to CircleCI.

**Comment by rgreinho** [comment]
Duplicate of #79.
