### ISSUE TITLE
Update Footer

### ISSUE THREAD

**Issue by 2echoi** [request-yo-racks/web#77]
Issue Type
----------
- Feature request

Current Behavior
----------------

The footer displays links to the social media and contact information.

Expected Behavior
-----------------

The footer should be user-friendly and easy to navigate. Also, the users can contact the team quickly.

Possible Solution
-----------------
• Add a form inside the footer.
• Add the link to Open Austin.
• Add contact information box, including full name, email address, and a message box.

**Comment by rgreinho** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/request-yo-racks/web/issues/32 (Update the global layout), and https://github.com/request-yo-racks/web/issues/62 (Change footer layout).

**Comment by rgreinho** [comment]
The footer will be updated as per the v2 design (#82).

**Comment by rgreinho** [comment]
Assigned to @toughee.

**Comment by rgreinho** [comment]
@Toughee Have you already started to work on it? 

If yes, that would be great if you could push your changes so that I can merge with mine. If not I'd to take this issue since I am currently working on the main layout.

**Comment by Toughee** [comment]
I was working on it. But I just noticed that a PR was already made for the issue
