### ISSUE TITLE
Redesign the map and address components

### ISSUE THREAD

**Issue by UX-Chris** [request-yo-racks/web#80]
Issue Type
----------

- Feature request

Current Behavior
----------------

The map and addresses are side by side and use standard visuals.

Expected Behavior
-----------------

More visually appealing components for a better user experience.

Possible Solution
-----------------

The layout of the components could be changed and visuals improve the components.

**Comment by rgreinho** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @rgreinho.

Possibly related issues are https://github.com/request-yo-racks/web/issues/53 (Give some style to the preview component), and https://github.com/request-yo-racks/web/issues/10 (Turn the preview component into its own element).

**Comment by rgreinho** [comment]
Done via #165.
