### ISSUE TITLE
Simplify the footer icon CSS

### ISSUE THREAD

**Issue by UX-Chris** [request-yo-racks/web#83]
Issue Type
----------

- Feature request

Current Behavior
----------------

The social media icons and Github photo use different classes, social-icons and social-icons-image.

Expected Behavior
-----------------

All of the icons should use the same class, social-icons, so they share the same style.

Possible Solution
-----------------

Create CSS rules to make the image and the icons behave the same way.

Steps to Reproduce (for bugs)
-----------------------------

1. Open my-app.html
2. Scroll to the social-icons CSS rules

Context
-------

Ensure that the icons are displayed the same way.

Your Environment
----------------

* Version used: e1c1609
* Browser Name and version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): El Capitan 10.11.6

**Comment by rgreinho** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @rgreinho.

Possibly related issues are https://github.com/request-yo-racks/web/pull/69 (Change Footer Icons and Alignment), https://github.com/request-yo-racks/web/issues/77 (Update Footer), and https://github.com/request-yo-racks/web/issues/62 (Change footer layout).
