### ISSUE TITLE
Create a custom icon for the Github logo

### ISSUE THREAD

**Issue by UX-Chris** [request-yo-racks/web#84]
Issue Type
----------

- Feature request

Current Behavior
----------------

The Github logo is currently an image file.

Expected Behavior
-----------------

The icon should be an icon file, the same as Facebook and Twitter.

Possible Solution
-----------------

Create a custom icon for the Github logo.

Context
-------

This makes all of the icons so they are not image files and will behave correctly.

**Comment by UX-Chris** [comment]
I saw that you can make custom iconsets and thought this may include adding custom icons. This doesn't appear possible and we will have to continue using the image file for the Github icon.

**Comment by rgreinho** [comment]
What about using [stackicons](http://stackicons.com/) for the GiotHub icon (and possible other missing social icons)?

**Comment by rgreinho** [comment]
I forgot about this one for a minute, but [fontawesome](https://fontawesome.com) is **REALLY** awesome!

The [instructions](https://fontawesome.com/get-started/web-fonts-with-css) are clear and the Github icon is [here](https://fontawesome.com/icons/github?style=brands).

**Comment by UX-Chris** [comment]
Oh yeah, of course! I'll switch all 3 over so they behave the same.
