### ISSUE TITLE
Use WebPack to bundle the project

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#86]
Issue Type
----------

- Feature request

Current Behavior
----------------

The project uses the polymer cli.

Expected Behavior
-----------------

Use webpack to bundle the project. This would also bring the benefit of being able to properly setup a developer environment for the project.

Possible Solution
-----------------

* https://webpack.js.org/loaders/polymer-webpack-loader/
* http://robdodson.me/how-to-use-polymer-with-webpack/
* https://codeburst.io/polymer-skeleton-webpack-postcss-service-workers-and-the-future-50189fbea23f

**Comment by Toughee** [comment]
Hello @rgreinho! I would like to resolve this issue.

**Comment by rgreinho** [comment]
Switching to React/NextJS made this issue obsolete.
