### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#88]
Issue Type
----------

- Bug report
- Feature request
It's almost kind of both :)

Current Behavior
----------------

The site displays the default Polymer icon:
<img width="109" alt="image" src="https://user-images.githubusercontent.com/6969134/39878351-be9a46b2-543d-11e8-9ac2-27feefba406f.png">

Expected Behavior
-----------------

We have a nice RYR logo, we should use it.

Possible Solution
-----------------

Replace the `image/favicon.ico` file.

**Comment by Toughee** [comment]
Added new favicon file using the RYR logo. Also added icos for Apple, Android and Microsoft platforms. Making a pull request now.
