### ISSUE TITLE
Rename application

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#89]
Issue Type
----------

- Bug report
- Feature request
Kind of both.

Current Behavior
----------------

The name oif the app is "My App"
<img width="109" alt="image" src="https://user-images.githubusercontent.com/6969134/39878516-34b802a8-543e-11e8-9d32-aad7741c8227.png">

Expected Behavior
-----------------

The name should be "RYR"

Possible Solution
-----------------

Edit the `manifest.json` file.

**Comment by Toughee** [comment]
Updated the manifest.json file to the name you requested. Making a pull request now
