### ISSUE TITLE
Add svg logo

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/web#93]
Issue Type
----------

- Feature request

Current Behavior
----------------

We only have the logos in `.png` for each sizes we needed.

Expected Behavior
-----------------

An `.svg` version of the logos will be useful for creating other versions or new material.

**Comment by 2echoi** [comment]
[svg_images.zip](https://github.com/request-yo-racks/web/files/1997174/svg_images.zip)
Here are zip file for svg images.

**Comment by rgreinho** [comment]
@2echoi Put the images in the `images/logos` folder and send a PR.
